Update style.css
when I tried to do "git push origin develop" it didn't work. 
I got this msg:
  ! [rejected]        develop -> develop (non-fast-forward)
error: failed to push some refs to 'https://github.com/MeryamWazeen/layout_search-bar-airbnb.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

So i made the changes here directly and still only one test is passed